version: '3.8'
networks:
  default:
    external: true
    name: swarm-test-network
    driver: bridge
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 9091:3000
    expose:
      - 9091
  gateway-proxy:
    build:
      context: ../
      dockerfile: ./dev/Dockerfile.dev
    volumes:
      - ../:/usr/src/app
    ports:
      - 4000:4000
    expose:
      - 4000
    image: ethersphere/gateway-proxy
    container_name: gateway-proxy
    command: npm start
